/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author mmuzaki.a
 */
public class AplikasiBukuAlamatGUI extends javax.swing.JFrame {

    /**
     * Creates new form AplikasiBukuAlamatGUI
     */
    public AplikasiBukuAlamatGUI() {
        initComponents();
        textNama.requestFocus();
        buttonTableSimpan.setEnabled(false);
        buttonTableEdit.setEnabled(false);
        buttonTableHapus.setEnabled(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textNama = new javax.swing.JTextField();
        textHubungan = new javax.swing.JTextField();
        textEmail = new javax.swing.JTextField();
        buttonInput = new javax.swing.JButton();
        buttonDelete = new javax.swing.JButton();
        buttonKeluar = new javax.swing.JButton();
        buttonTableEdit = new javax.swing.JButton();
        buttonTableHapus = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        buttonTableSimpan = new javax.swing.JButton();
        textSearch = new javax.swing.JTextField();
        textAlamat = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        textNohp = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        buttonImport = new javax.swing.JButton();
        buttonExport = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 165, 0));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "Hubungan", "Lokasi", "Alamat", "Email", "Nomor HP"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Nama");

        jLabel2.setText("Lokasi");

        jLabel3.setText("Alamat");

        jLabel4.setText("No.Hp");

        textHubungan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textHubunganActionPerformed(evt);
            }
        });

        textEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textEmailKeyReleased(evt);
            }
        });

        buttonInput.setText("Input");
        buttonInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInputActionPerformed(evt);
            }
        });

        buttonDelete.setText("Delete");
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });

        buttonKeluar.setText("Keluar");
        buttonKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKeluarActionPerformed(evt);
            }
        });

        buttonTableEdit.setText("Edit");
        buttonTableEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTableEditActionPerformed(evt);
            }
        });

        buttonTableHapus.setText("Hapus");
        buttonTableHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTableHapusActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(165, 42, 42));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("APLIKASI BUKU ALAMAT");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel5)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        buttonTableSimpan.setText("Simpan");
        buttonTableSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTableSimpanActionPerformed(evt);
            }
        });

        textSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textSearchKeyReleased(evt);
            }
        });

        jLabel6.setText("Hubungan");

        jLabel7.setText("Email");

        textNohp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textNohpKeyReleased(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Silahkan Input", "Rumah", "Kantor", "Sekolah", "Kampus" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("SEARCH");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        buttonImport.setText("Import");
        buttonImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonImportActionPerformed(evt);
            }
        });

        buttonExport.setText("Export");
        buttonExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(buttonImport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(buttonInput))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(buttonExport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(buttonDelete))
                                .addGap(37, 37, 37))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6))
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(14, 14, 14)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(textHubungan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                                    .addComponent(textNama, javax.swing.GroupLayout.Alignment.TRAILING)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(textAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(textNohp)
                                            .addComponent(jComboBox1, 0, 134, Short.MAX_VALUE)
                                            .addComponent(textEmail))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(buttonTableSimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonTableEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonTableHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonKeluar)
                        .addGap(78, 78, 78))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonTableEdit)
                            .addComponent(buttonTableHapus)
                            .addComponent(buttonTableSimpan)
                            .addComponent(buttonKeluar)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(textNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(textHubungan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(textAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(textEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(textNohp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonInput)
                            .addComponent(buttonDelete))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonImport)
                            .addComponent(buttonExport))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textHubunganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textHubunganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textHubunganActionPerformed

    private void buttonTableHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTableHapusActionPerformed
       DefaultTableModel model = (DefaultTableModel) jTable1.getModel(); // Mengambil model tabel default
       if (jTable1.getSelectedRow()==-1) { // Memeriksa apakah ada baris yang dipilih
           if (jTable1.getRowCount()==0) { // Memeriksa apakah tabel kosong
               //dikosongkan karena button di set false saat aplikasi pertama jalan
           }else{
               JOptionPane.showMessageDialog(null, "Pilih data yang dihapus");
           }
       }else{
           int a=JOptionPane.showConfirmDialog(null,"Yakin ingin menghapus data", "select", JOptionPane.YES_NO_OPTION);
            if (a==0)
            {
                model.removeRow(jTable1.getSelectedRow());
                JOptionPane.showMessageDialog(null, "Data berhasil di hapus ");
            }
 
       }

    }//GEN-LAST:event_buttonTableHapusActionPerformed

    private void buttonInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInputActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel(); // Mengambil model tabel default
        if (textNama.getText().trim().equals("") || textHubungan.getText().trim().equals("") || jComboBox1.getSelectedItem().equals("Silahkan Input") || textAlamat.getText().trim().equals("") || textEmail.getText().trim().equals("") || textNohp.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Isi semua data terlebih dahulu"); // Memeriksa apakah ada field input yang kosong
        }else{
            model.addRow(new Object[] {textNama.getText(), textHubungan.getText(), jComboBox1.getSelectedItem(), textAlamat.getText(), textEmail.getText(), textNohp.getText()}); // Menambahkan baris baru ke tabel dengan data dari input fields
            
            textNama.setText("");
            jComboBox1.setSelectedItem("Silahkan Input");
            textHubungan.setText("");
            textEmail.setText("");
            textAlamat.setText("");
            textNohp.setText("");
            
            buttonTableSimpan.setEnabled(true);
            buttonTableEdit.setEnabled(true);
            buttonTableHapus.setEnabled(true);
            
            JOptionPane.showMessageDialog(null, "Data berhasil di input");
        }
        
    }//GEN-LAST:event_buttonInputActionPerformed

    private void buttonTableEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTableEditActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel(); // Mengambil model tabel default
        if (jTable1.getSelectedRow()==-1) { // Memeriksa apakah ada baris yang dipilih
            if (jTable1.getRowCount()==0) { // Memeriksa apakah tabel kosong
                //dikosongkan karena button di set false saat aplikasi pertama jalan
            }else{
                JOptionPane.showMessageDialog(null, "Pilih data terlebih dulu");
            }
        }else{
            textNama.setText(model.getValueAt(jTable1.getSelectedRow(), 0).toString());
            textHubungan.setText(model.getValueAt(jTable1.getSelectedRow(), 1).toString());
            jComboBox1.setSelectedItem(model.getValueAt(jTable1.getSelectedRow(), 2).toString());
            textAlamat.setText(model.getValueAt(jTable1.getSelectedRow(), 3).toString());
            textEmail.setText(model.getValueAt(jTable1.getSelectedRow(), 4).toString());
            textNohp.setText(model.getValueAt(jTable1.getSelectedRow(), 5).toString());
            
            textNama.requestFocus();
            
            buttonInput.setEnabled(false);
        }
        
        
    }//GEN-LAST:event_buttonTableEditActionPerformed

    //agar button edit tidak error
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel(); // Mengambil model tabel default
    }//GEN-LAST:event_jTable1MouseClicked

    private void buttonTableSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTableSimpanActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel(); // Mengambil model tabel default
        if (jTable1.getSelectedRow()==-1) { // Memeriksa apakah ada baris yang dipilih
            if (jTable1.getRowCount()==0) { // Memeriksa apakah tabel kosong
                //dikosongkan karena button di set false saat aplikasi pertama jalan
            }else{
                JOptionPane.showMessageDialog(null, "Pilih data terlebih dulu");
            }
        }else{
            model.setValueAt(textNama.getText(), jTable1.getSelectedRow(), 0);
            model.setValueAt(textHubungan.getText(), jTable1.getSelectedRow(), 1);
            model.setValueAt(jComboBox1.getSelectedItem(), jTable1.getSelectedRow(), 2);
            model.setValueAt(textAlamat.getText(), jTable1.getSelectedRow(), 3);
            model.setValueAt(textEmail.getText(), jTable1.getSelectedRow(), 4);
            model.setValueAt(textNohp.getText(), jTable1.getSelectedRow(), 5);
            
            textNama.setText("");
            jComboBox1.setSelectedItem("Silahkan Input");
            textHubungan.setText("");
            textEmail.setText("");
            textAlamat.setText("");
            textNohp.setText("");
            
            buttonInput.setEnabled(true);
            
            JOptionPane.showMessageDialog(null, "Data tabel berhasil di edit");
            
        }
        
    }//GEN-LAST:event_buttonTableSimpanActionPerformed

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
        textNama.setText("");
        textHubungan.setText("");
        jComboBox1.setSelectedItem("Silahkan Input");
        textAlamat.setText("");
        textEmail.setText("");
        textNohp.setText("");
        textNama.requestFocus();
    }//GEN-LAST:event_buttonDeleteActionPerformed

    private void buttonKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKeluarActionPerformed
        int a=JOptionPane.showConfirmDialog(null,"Apakah yakin ingin keluar", "select", JOptionPane.YES_NO_OPTION);
        if (a==0)
        {
         System.exit(0); // Jika pengguna memilih "Yes" (0), keluar dari aplikasi
        }
    }//GEN-LAST:event_buttonKeluarActionPerformed

    private void textSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textSearchKeyReleased
        DefaultTableModel model=(DefaultTableModel) jTable1.getModel(); // Mengambil model tabel default
        TableRowSorter<DefaultTableModel> model1=new TableRowSorter<>(model); // Membuat objek TableRowSorter dengan model tabel sebagai argumen
        jTable1.setRowSorter(model1); // Mengatur TableRowSorter sebagai sorter untuk jTable1
        model1.setRowFilter(RowFilter.regexFilter((textSearch.getText()))); // Mengatur filter pada TableRowSorter berdasarkan teks yang dimasukkan pada textSearch
    }//GEN-LAST:event_textSearchKeyReleased

    private void textNohpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textNohpKeyReleased
        if (Character.isAlphabetic(evt.getKeyChar())){ // Memeriksa apakah karakter yang dimasukkan adalah alfabet
            evt.consume(); // Jika karakter alfabet dimasukkan, konsumsi event dan tampilkan pesan kesalahan
            JOptionPane.showMessageDialog(null, "Isi dengan angka");
            textNohp.setText("");
        }
    }//GEN-LAST:event_textNohpKeyReleased

    private void buttonImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonImportActionPerformed
        try {
            BufferedReader br = new BufferedReader(new FileReader("ImportData.txt")); // Membaca file "ImportData.txt" menggunakan BufferedReader
            
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel(); // Mengambil model tabel default
            Object[] lines = br.lines().toArray(); // Mengkonversi baris dari file menjadi array objek
            
            for (int i = 0; i < lines.length; i++) { // Looping melalui setiap baris, membaginya menjadi array string, dan menambahkannya ke model tabel
                String[] row = lines[i].toString().split(" ");
                model.addRow(row); // Menambahkan baris ke model tabel
                JOptionPane.showMessageDialog(null, "Data Berhasil Import");
            }
           
          br.close(); // Menutup BufferedReader setelah selesai membaca file
            
        } catch (Exception e) {
            System.err.println("Error: " + e.getMessage()); // Menangkap dan mencetak pesan kesalahan jika terjadi eksepsi
        }
    }//GEN-LAST:event_buttonImportActionPerformed

    private void buttonExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExportActionPerformed
        try {
            BufferedWriter bw = new BufferedWriter(new FileWriter("ExportData.txt")); // Membuat BufferedWriter untuk menulis ke file "ExportData.txt"
            
            for(int i = 0; i < jTable1.getRowCount(); i++) { // Loop baris
                for(int j = 0; j < jTable1.getColumnCount(); j++) { // Loop kolom
                    bw.write(jTable1.getValueAt(i, j).toString()+" "); // Menulis nilai dari setiap sel dalam tabel ke file, dipisahkan oleh spasi
                }
                
                bw.newLine(); // Menambahkan baris baru setelah menulis semua kolom untuk satu baris
            }
            
           JOptionPane.showMessageDialog(null, "Data Berhasil Export");
           bw.close(); // Menutup BufferedWriter setelah selesai menulis ke file
           
        } catch (Exception e) {
            System.err.println("Error: " + e.getMessage()); // Menangkap dan mencetak pesan kesalahan jika terjadi eksepsi
        }
    }//GEN-LAST:event_buttonExportActionPerformed

    private void textEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textEmailKeyReleased
        //if (Character.isAlphabetic(evt.getKeyChar())){ // Memeriksa apakah karakter yang dimasukkan adalah alfabet
        //    evt.consume(); // Jika karakter alfabet dimasukkan, konsumsi event dan tampilkan pesan kesalahan
        //    JOptionPane.showMessageDialog(null, "Isi dengan angka");
        //    textEmail.setText("");
        //}
    }//GEN-LAST:event_textEmailKeyReleased

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        //if (jComboBox1.getSelectedItem().equals("Kantor")) { // Memeriksa apakah opsi yang dipilih pada JComboBox adalah "Kantor"
        //    textFax.setEnabled(true);
        //}else{
        //    textFax.setEnabled(false);
        //}
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiBukuAlamatGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiBukuAlamatGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiBukuAlamatGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiBukuAlamatGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiBukuAlamatGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonExport;
    private javax.swing.JButton buttonImport;
    private javax.swing.JButton buttonInput;
    private javax.swing.JButton buttonKeluar;
    private javax.swing.JButton buttonTableEdit;
    private javax.swing.JButton buttonTableHapus;
    private javax.swing.JButton buttonTableSimpan;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField textAlamat;
    private javax.swing.JTextField textEmail;
    private javax.swing.JTextField textHubungan;
    private javax.swing.JTextField textNama;
    private javax.swing.JTextField textNohp;
    private javax.swing.JTextField textSearch;
    // End of variables declaration//GEN-END:variables
}
